[1주차 과제] 로그인 및 회원가입 페이지 구현
IN-SOPT-ANDROID/daehwan.gye pull request #3
Opened 2022-10-02 12:27 UTC by daehwan2yo

## As is

## To be
- View 구성
  - Login Page
  - SignUp Page
  - My Page
- Activity 구현

## 관련 링크
- #1

2022-10-02 18:10 UTC, 2zerozu approved these changes
처음 보는 코드들에 머리가 어질어질 빙글빙글 ~
자바랑 enum 클래스를 안 써봐서 이해하느라 오래 걸렸어요
많이 배워갑니다!!!!!!

2022-10-02 18:10 UTC, 2zerozu commented on app/src/main/res/layout/activity_sign_up.xml
> +        android:id="@+id/signup_tv_title"
보통 TextView id값은 tv로 써줍니다!
tv_signup_tv_title로 써주는 건 어떨까요!!
(Activity에서 binding할 때 한 눈에 알아보기 쉽습니다!)

2022-10-02 18:10 UTC, 2zerozu commented on app/src/main/res/layout/activity_sign_up.xml
> +        android:id="@+id/signup_et_id"
EditText id값은 et!
et_signup_id가 어떨까요!!

2022-10-02 18:10 UTC, 2zerozu commented on app/src/main/res/layout/activity_sign_up.xml
> +        android:inputType="text"
👍🏻👍🏻

2022-10-02 18:10 UTC, 2zerozu commented on app/src/main/res/values/strings.xml
> +    <string name="id">아이디</string>
string값 추가 좋습니다👍🏻

2022-10-02 18:10 UTC, 2zerozu commented on app/src/main/res/layout/activity_sign_up.xml
> +        android:inputType="textPassword"
👍🏻👍🏻👍🏻👍🏻👍🏻

2022-10-02 18:10 UTC, 2zerozu commented on app/src/main/res/layout/activity_my_page.xml
> +        android:id="@+id/my_page_profile_image"
ImageView는 iv!
iv_my_page_profile은 어떨까요!

2022-10-02 18:10 UTC, 2zerozu commented on app/src/main/res/layout/activity_my_page.xml
> +        app:layout_constraintDimensionRatio="1:1"
👍🏻👍🏻

2022-10-02 18:10 UTC, 2zerozu commented on app/src/main/res/layout/activity_login.xml
> +        android:id="@+id/btn_signUp"
xml에서는 snake case라서 btn_signup이 좋을 것 같습니다!

2022-10-02 18:10 UTC, 2zerozu commented on app/src/main/java/org/sopt/sample/week1/login/LoginActivity.kt
> +                startActivity(toMyPageView)
```suggestion
                startActivity(toMyPageView)
                finish()
```

MyPage뷰로 이동되어도 Login뷰는 그대로 남아있겠네요!
`finish()`를 이용해보면 좋을 것 같아용

2022-10-02 18:10 UTC, 2zerozu commented on app/src/main/java/org/sopt/sample/week1/signup/SignUpPolicy.kt
> +}
진짜 이런 생각을 어떻게 하신거죠??
우와..

2022-10-02 18:10 UTC, 2zerozu commented on app/src/main/java/org/sopt/sample/week1/mypage/MyPageActivity.kt
> +            intent.getSerializableExtra(Constants.MBTI.value).toString()
우와ㅏ `getSerializableExtra` 처음봐요 배워갑니다ㅏ
구글 왈, 데이터 클래스를 직렬화해서 보내줄 때 `getSerializableExtra`를 이용해서 데이터를 전달받는다고 하네요

2022-10-02 18:10 UTC, 2zerozu commented on app/src/main/java/org/sopt/sample/week1/common/MBTI.kt
> +                mbti.toString() == target.uppercase()
우와 이렇게도 대문자를 바꿔줄 수 있겠네요

2022-10-02 18:10 UTC, 2zerozu commented on app/src/main/java/org/sopt/sample/week1/signup/SignUpActivity.kt
> +    private val signUpPolicy = SignUpPolicy(idMin = 6, idMax = 10, pwMin = 8, pwMax = 12)
이렇게 할 생각을 하다니...😮

2022-10-02 18:10 UTC, 2zerozu commented on app/src/main/java/org/sopt/sample/week1/signup/SignUpActivity.kt
> +        private val WRONG_MBTI = "없는 MBTI 가 입력되었습니다."
ㅋㅋㅋㅋ제 mbti는 CUTE인데요.

2022-10-02 18:10 UTC, 2zerozu commented on app/src/main/java/org/sopt/sample/week1/login/LoginActivity.kt
> +        if (intent.hasExtra(Constants.ID.value) && intent.hasExtra(Constants.PASSWORD.value)) {
`hasExtra`가 null 체크하는 거 맞나요? 검색해도 검색 정보가 적네요 ㅠ

2022-10-02 20:02 UTC, 2zerozu commented on app/src/main/java/org/sopt/sample/week1/signup/SignUpActivity.kt
> +                    startActivity(toLoginView)
```suggestion
                    finish()
```

현재 Login뷰가 살아있기 때문에 `startActivity`보다는 `finish()`를 사용하는 게 좋을 것 같습니다!
SignUpActivity를 종료해주면 Login으로 가집니다

2022-10-03 04:39 UTC, l2hyunwoo requested changes
몇몇 부분 중복이 있는 것 같아서 변경하면 좋을 것 같습니다. 흥미로운 코드들이 많네요 한번 같이 이야기해보죠

2022-10-03 04:39 UTC, l2hyunwoo commented on app/src/main/AndroidManifest.xml
> +                android:value="" />
혹시 JNI 사용해서 NativeActivity 사용하신적이 계신가요? 이 부분은 NDK에서 공유라이브러리 파일을 지정할 때 사용하는 메타데이터인데 이런걸 집어넣으시다니 신기하네요ㅋㅋ

2022-10-03 04:39 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/sample/week1/common/Constants.kt
> +}
```suggestion
enum class Constants(val value: String) {
    ID("id"),
    PASSWORD("password"),
    MBTI("mbti");
}
```

Lint

2022-10-03 04:39 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/sample/week1/common/MBTI.kt
> +                mbti.toString() == target.uppercase()
왜 이런 로직을 적었는지는 알겠습니다! 

다만 INVALID같은 경우는 조금 더 명시적으로 error throw를 해서 외부에서 이 from 함수를 사용할 때 적절하지 못한 입력값이 들어가는 경우 예외 처리하는 케이스로 가는 것이 설계목적에 더 부합할 것 같은데 어떠신가요?

2022-10-03 04:39 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/sample/week1/login/LoginActivity.kt
> +        if (intent.hasExtra(Constants.ID.value) && intent.hasExtra(Constants.PASSWORD.value)) {
이 부분은 단순히 키값이 있는 지 비교하는 로직이 들어가는 것 같아서 enum class 대신 const val정도로만 처리해도 될 것 같습니다.

```kotlin
    companion object {
        private const val ID = "id"
    }
```

2022-10-03 04:39 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/sample/week1/login/LoginActivity.kt
> +                ?: throw java.lang.IllegalArgumentException("id expected")
```suggestion
                ?: throw IllegalArgumentException("id expected ${intent.getStringExtra(Constants.ID.value)}")
```

- Kotlin exception을 활용해주세요
- Exception이 터질 경우 해당 에러가 발생한 원인이 되는 값을 찍어주는 것이 좋습니다.

2022-10-03 04:39 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/sample/week1/login/LoginActivity.kt
> +            startActivity(toSignUpView)
네이밍 완전 좋습니다

2022-10-03 04:39 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/sample/week1/login/LoginActivity.kt
> +                return@setOnClickListener
early return 방식 아주 좋습니다

2022-10-03 04:39 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/sample/week1/login/LoginActivity.kt
> +                toMyPageView.putExtra(Constants.MBTI.value, insertedMbti)
```suggestion
                val toMyPageView = Intent(this, MyPageActivity::class.java)
                    .putExtra(Constants.ID.value, insertedId)
                    .putExtra(Constants.MBTI.value, insertedMbti)
```

Constants enum class를 만들어놓았는에 외부에서 계속 class 내부 value를 직접 사용하는 케이스가 많은 것 같습니다.

2022-10-03 04:39 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/sample/week1/login/LoginActivity.kt
> +                Toast.makeText(this.applicationContext, "로그인 정보가 올바르지 못합니다.", Toast.LENGTH_SHORT)
오 Toast에 applicationContext 사용하는 것은 어디에서 아신 것인가요?

2022-10-03 04:39 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/sample/week1/login/LoginActivity.kt
> +                // login success
주석 적절하게 잘 달아주셨습니다.

2022-10-03 04:39 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/sample/week1/mypage/MyPageActivity.kt
> +        setContentView(R.layout.activity_my_page)
이 부분 중복인 것 같네요ㅋㅋㅋ

2022-10-03 04:39 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/sample/week1/signup/SignUpActivity.kt
> +    }
이렇게 적는 경우도 있는데(Java에서는 static block이 상단에 위치하는게 컨벤션이었던 것 같은데유), 코틀린에서는 Companion object가 클래스 최하단에 있는 것이 주 컨벤션이긴 합니다. 다만 이렇게 적으시는 분들도 많아서 취사선택 하시면 될 것 같아요.

2022-10-03 04:39 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/sample/week1/signup/SignUpActivity.kt
> +        setContentView(R.layout.activity_sign_up)
중복!

2022-10-03 04:39 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/sample/week1/signup/SignUpActivity.kt
> +                ) {
이 경우도 회원가입 정책에 포함되어야 하지 않을까요? 회원가입 정책에 길이 제한만 있어서 SnackBar에 들어가는 문구 처리하는 로직을 응집시키기가 어려운 것 같습니다.

2022-10-03 04:39 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/sample/week1/signup/SignUpPolicy.kt
> +class SignUpPolicy(val idMin: Int, val idMax: Int, val pwMin: Int, val pwMax: Int) {
data class 사용하셔도 될 것 같습니다. toString 등 자동으로 구현해주는 메서드들이 있어서 디버깅하실 때 편해요

2022-10-03 04:39 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/sample/week1/signup/SignUpPolicy.kt
> +        this.signupEtPassword.text.length in pwMin..pwMax
👍🏻

2022-10-03 04:39 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/sample/week1/signup/SignUpPolicy.kt
> +    fun idInvalid(binding: ActivitySignUpBinding) = !binding.idSucceed()
```suggestion
    fun isIdInvalid(binding: ActivitySignUpBinding) = !binding.idSucceed()
```

판별하는 함수이니 is를 접두사로 붙이는건 어떤가요?

2022-10-03 04:44 UTC, l2hyunwoo commented
+) 추가적으로 intent-filter main, launcher 안 걸려있던데 실행하셔서 테스트 하셨나요?

2022-10-03 04:47 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/sample/week1/common/MBTI.kt
> +                mbti.toString() == target.uppercase()
[깔끔한 코틀린에서의 예외처리 방법](https://medium.com/harrythegreat/kotlin-runcatching%EA%B3%BC-result-%ED%83%80%EC%9E%85-ab261f47efa8) 참고하기

2022-10-05 00:12 UTC, daehwan2yo commented on app/src/main/res/layout/activity_sign_up.xml
> +        android:id="@+id/signup_tv_title"
tv 가 중복되어지는 것 같아서, `tv_signup_title` 으로 하겠습니다 ~

2022-10-05 00:15 UTC, daehwan2yo commented on app/src/main/java/org/sopt/sample/week1/mypage/MyPageActivity.kt
> +            intent.getSerializableExtra(Constants.MBTI.value).toString()
이게 보니까 32 버전부터인가? `@Deprecated` 된 메서드더라구요 ㅎ 뒤에 타입 명시를 같이 해주는 형식으로 바뀌었는데,
저희가 쓰는 버전에서는 큰 문제가 없는것같습니다~
(저도 어떨결에 찾게된 메서드랍니다..ㅎ)

2022-10-05 00:16 UTC, daehwan2yo commented on app/src/main/java/org/sopt/sample/week1/login/LoginActivity.kt
> +        if (intent.hasExtra(Constants.ID.value) && intent.hasExtra(Constants.PASSWORD.value)) {
Constants.ID 의 값을 갖고있는지 여부를 확인하는 메서드 입니다.
(null 체크 보다는 key 가 있는지 확인?) 
저도 처음써봐서 더 리서치하고 공유드릴게요~

2022-10-05 00:17 UTC, daehwan2yo commented on app/src/main/AndroidManifest.xml
> +                android:value="" />
아 이거 처음에 Empty 말고 `Login Activity` 로 템플릿을 눌러봤는데 그때 다 지우지못하고 남은것아닐까 생각듭니다.,ㅎ

2022-10-05 00:18 UTC, daehwan2yo commented on app/src/main/AndroidManifest.xml
> +                android:value="" />
(지워야겠네요)

2022-10-05 00:19 UTC, daehwan2yo commented on app/src/main/java/org/sopt/sample/week1/common/Constants.kt
> +}
개인적인 컨벤션인데요,
MBTI 이 후에 다른 상수가 추가될때 `,` 를 안쓰는 실수를 방지하고자 명시적으로 띄어뒀었습니다 ㅎㅎ 
(물론 컴파일에서 잡히는 오류긴하지만 ㅎㅎ)

2022-10-05 00:20 UTC, daehwan2yo commented on app/src/main/java/org/sopt/sample/week1/common/MBTI.kt
> +                mbti.toString() == target.uppercase()
좋은 방향인것같아요! 아직은 `코틀린 예외처리` 가 익숙치않았는데,
공유주신 링크 바탕으로 리서치를 해보고 반영해두겠습니다 ㅎㅎ

2022-10-05 00:22 UTC, daehwan2yo commented on app/src/main/java/org/sopt/sample/week1/login/LoginActivity.kt
> +        if (intent.hasExtra(Constants.ID.value) && intent.hasExtra(Constants.PASSWORD.value)) {
`Constans` enum으로 global 하게 쓰는 상수들을 모아뒀었는데요,
`const val`는 런타임이 아니라 컴파일 단계에서 상수를 처리 하는 방식이네요! 배워갑니다 ㅎㅎ

2022-10-05 00:23 UTC, daehwan2yo commented on app/src/main/java/org/sopt/sample/week1/login/LoginActivity.kt
> +                return@setOnClickListener
return 으로 끝내고싶었으나, 어떤 것을 return 하는지는 자동완성으로 해당 코드가 되었는데,
`@setOnClickListener` 저부분의 의미를 여쭤봐도 될까요?

2022-10-05 00:24 UTC, daehwan2yo commented on app/src/main/java/org/sopt/sample/week1/login/LoginActivity.kt
> +                toMyPageView.putExtra(Constants.MBTI.value, insertedMbti)
그러게요..! 이부분은 좀 더 고민해보겠습니다..! 말씀감사합니다

2022-10-05 00:27 UTC, daehwan2yo commented on app/src/main/java/org/sopt/sample/week1/login/LoginActivity.kt
> +                Toast.makeText(this.applicationContext, "로그인 정보가 올바르지 못합니다.", Toast.LENGTH_SHORT)
우선 원리보다는 구글링에서 찾은 부분이라 .. 리서치가 필요한 부분인데요,
Spring 에서 활용되는 Context 와 같은 느낌일거라 생각되었는데, 잠깐 보니 생명주기랑 관련있는 부분 인것같네요.
리서치에서 wiki 에 정리해두겠습니다~

2022-10-05 00:27 UTC, daehwan2yo commented on app/src/main/java/org/sopt/sample/week1/signup/SignUpActivity.kt
> +    }
오.. 코틀린 컨벤션에 맞춰가보도록 하겠습니다!

2022-10-05 00:28 UTC, daehwan2yo commented on app/src/main/java/org/sopt/sample/week1/signup/SignUpActivity.kt
> +                ) {
아 그러네요, 반영해두겠습니다~

2022-10-05 00:30 UTC, daehwan2yo commented
- https://github.com/IN-SOPT-ANDROID/daehwan.gye/pull/3#issuecomment-1264929455
말씀 주신 부분들이 누락이 된거일까요?? 실행은 정상적으로 잘 되었습니다 ~

2022-10-06 18:09 UTC, 2zerozu commented on app/src/main/res/layout/activity_sign_up.xml
> +        android:id="@+id/signup_tv_title"
> tv 가 중복되어지는 것 같아서, `tv_signup_title` 으로 하겠습니다 ~

어우 밤에 써서 엉뚱하게 적어놨네용,, `tv_signup_title` 맞아요 ㅎ..

2022-10-06 22:14 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/sample/week1/login/LoginActivity.kt
> +                return@setOnClickListener
return을 할 때 어떤 단위에서 return을 할 지 결정할 수 있습니다.

```kotlin
fun sampleFunction() {
    binding.btn.setOnClickListener {
        return
        // 이 리턴은 setOnClickListener를 끝내는 것인지, sampleFunction을 끝내는 것인지 명확히 컨텍스트를 알 수 없음
        // return@setOnClickListener로 끝내는 지점(label)을 명시
    }
}
```

2022-10-07 02:28 UTC, l2hyunwoo commented
음 일단 알겠습니다! intent-filter가 없어도 실행이 되는군요...제가 나중에 클론받고 실행한번 해볼게요!

2022-10-09 06:24 UTC, daehwan2yo commented
@l2hyunwoo 
- https://github.com/IN-SOPT-ANDROID/daehwan.gye/pull/3#issuecomment-1271029130
조사해보니, 어떤 Intent Type 을 활용하는 Activity 냐에 따라 IntentFilter 여부가 mandatory 혹은 optional 이 되나봅니다.
  - 현재 과제 중 활용한 Intent는 어떤 컴포넌트에 전달할지가 명확한 `Explicit Intent` 를 활용해서 별도의 Filter 가 필요하지 않음
  - 만약 다른 Application 을 활용하는 경우 대상 component 를 명시하기 어려움으로 `Implicit Intent` 를 활용, 이때는 Intent Filter 가 필수로 명시되어야함.

ref
- https://developer.android.com/guide/components/intents-filters?hl=en#Receiving

2022-10-09 06:26 UTC, l2hyunwoo approved these changes
참고자료 조사해주셔서 감사합니다!

2022-10-09 08:34 UTC, l2hyunwoo reviewed
👍🏻

2022-10-09 08:34 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/sample/week1/common/Mbti.kt
> +            values().any { mbti -> mbti.toString() == target }
네이밍 좋아!

2022-10-09 10:53 UTC, merged